language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ./build/tmp/

git:
  depth: false

deploy:
  # Deploy release to CurseForge
  - provider: script
    edge: true
    skip_cleanup: true
    script: ./gradlew deployCurseForge
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|[0-9]+\.[0-9]+\.[0-9]+.*?)$

  # Deploy release to GitHub (release)
  - provider: releases
    edge: true
    skip_cleanup: true
    file_glob: true
    file: build/libs/**/*
    token: "$GITHUB_TOKEN"
    release_notes_file: build/tmp/changelog.md
    overwrite: true
    on:
      tags: true
